<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Mon, 09 Jul 2012 18:16:42 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mem_change_button' => "Change...",
'mem_posts' => "Posts",
'm_overrride' => "Override group permission masks with...",
 ); 
