<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 13 Jul 2012 19:04:19 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'gallery_loci_album' => "Viewing Album:",
'gallery_loci_idx' => "Viewing Gallery Index",
'gallery_loci_si' => "Viewing Image:",
 ); 
