<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 13 Jul 2012 19:04:19 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'aff_title' => "Recommended Sites",
'discuss_title' => "Latest Discussions",
'in' => "in",
'last_reply_by' => "Last reply by",
'links_title' => "Site Navigation",
'online_breakdown' => "There are <strong>%s</strong> online users browsing:",
'online_split' => "%s members, %s visitors and %s anonymous users",
'online_title' => "Online Users",
'photo' => "Photo",
'poll_title' => "Website Poll",
'portal_title' => "Portal",
'posted_by' => "Posted by",
'replies' => "Replies",
'views' => "Views",
 ); 
